<!DOCTYPE html>
<html lang="fr">
    <head>
        <?php include 'templates/head.phtml'; ?>
    </head>
    <body>
        <header>
            <?php  include 'templates/header.phtml'; ?>
        </header>
        <main>
            <h1>Connexion</h1>
            <section class="login_section">
                <form id="login_form" method="POST">
                    <div class="email">
                        <label for="email" >Adresse e-mail</label>
                        <input type="text" name="email" value="" id="email" placeholder="exemple@mail.com"/>
                    </div>
                    <div class="password">
                        <div class="label_password">
                            <div>
                                <label for="password">Mot de passe</label>
                            </div>
                            <div class="hide_show">
                                <div class="hide password_display">
                                    <p class="password_hide">Masquer <i class="fas fa-eye"></i></p>
                                </div>
                                <div class="show">
                                    <p class="password_show">Afficher <i class="fas fa-eye-slash"></i></p>
                                </div>
                            </div>
                        </div>
                        <input type="password" name="password" id="password"/>
                    </div>
                    <div class="login_btn">
                        <button>Se connecter</button>
                    </div>
                    <div class="to_registration">
                        <a href="registration.php">Créer un compte</a>
                    </div>
                    <div class="error_small">
                        <small><?php if(isset($wrongConnection)):
                            echo $wrongConnection;
                            endif; ?>
                        </small>
                    </div>
                </form>
            </section>
        <script src="application/views/js/loginForm.js"></script>
        </main>
    </body>
</html>