<!DOCTYPE html>
<html lang="fr">
    <head>
        <?php include 'templates/head.phtml'; ?>
    </head>
    <body>
        <header>
            <?php  include 'templates/header.phtml'; ?>
        </header>
        <main>
            <div class="validation_message">
                <p>Merci pour votre commande, vous la recevrez d'ici peu.</p>
                <a href="index.php">Retour a l'accueil</a>
            </div>
        </main>
    </body>
</html>